### ISSUE TITLE
Building?

### ISSUE THREAD

**Issue by Noemata** [infinitespace-studios/VectorRumble#1]
Not able to build from the current repository release.  I have a broken link for the Content folder in the Shared project and when I bring in the Content pipeline build portion into the USP solution, I am not able to build the shaders using the monogame content pipeline build tool (GUI version).

**Comment by Noemata** [comment]
So I was able to get the shaders to build (after adding them into the content) by switching "ps_2_0" to "ps_4_0".  I'm getting a null reference when this executes:

parameters ["BaseTexture"].SetValue (sceneRenderTarget);

The BaseTexture registers is not mapped.  What is this supposed to be?

**Comment by dellis1972** [comment]
hi @Noemata which platform are you building for? I've only really tested this on Mac. We are working on the DekstopDX port now.

**Comment by Noemata** [comment]
x64 UWP, I did eventually get this working.
