### ISSUE TITLE
Localise for German

### ISSUE THREAD

**Issue by dellis1972** [infinitespace-studios/VectorRumble#5]

**Comment by ThodeC** [comment]
I can put my hand on it, if still needed

**Comment by dellis1972** [comment]
contributions always welcome :)

**Comment by ThodeC** [comment]
Allright, I just forked the repo, thanks! :)

I already found the string files, but where do I have to set the references, where the player chooes between english, spanish and german?

**Comment by dellis1972** [comment]
The User does not need to chose a language, it will be detected automatically from the operating systems settings. 

So we really just need a Strings.de.resx file which contains the translation.

**Comment by ThodeC** [comment]
Hello @dellis1972 

thanks for the clarification! :+1:
